### ISSUE TITLE
The background turns black

### ISSUE THREAD

**Issue by Lengdrich** [Tsuzat/NeoSolarized.nvim#13]
After installing the plugin and configuring it for this theme, my background has changed to this.

![image](https://user-images.githubusercontent.com/80807272/236216572-ee383714-029f-4c64-ac21-d7b6303fc77e.png)

this is my config:
```lua

  {
    "Tsuzat/NeoSolarized.nvim",
    event = "VeryLazy",

    config = function()
      require("NeoSolarized").setup({
        style = "dark",         -- "dark" or "light"
        -- transparent = true,     -- true/false; Enable this to disable setting the background color
        terminal_colors = true, -- Configure the colors used when opening a `:terminal` in Neovim
        enable_italics = false,  -- Italics for different hightlight groups (eg. Statement, Condition, Comment, Include, etc.)
        styles = {
          -- Style to be applied to different syntax groups
          comments = { italic = false },
          keywords = { italic = false },
          functions = { bold = true },
          variables = {},
          string = { italic = false },
          underline = true, -- true/false; for global underline
          undercurl = true, -- true/false; for global undercurl
        },
        -- Add specific hightlight groups
        -- on_highlights = function(highlights, colors)
        --   -- highlights.Include.fg = colors.red -- Using `red` foreground for Includes
        -- end,
      })
      -- vim.cmd [[ colorscheme NeoSolarized ]]
    end

  },


```

**Comment by Tsuzat** [comment]
As far as I know, it could of due to following reasons.
- As NeoSolarized is not your default colorscheme it could be possible something is overwriting the background.
- By default the background is transparent hence, it may be possible you are seeing this due to your terminal colorscheme setup.

Try setting up NeoSolarized as default colorscheme [see](https://github.com/Tsuzat/NeoSolarized.nvim#lazynvim) just to debug it. Try changing the transparency to `false` and try changing the style. I hope you may find your solution.

**Comment by Lengdrich** [comment]
yes, when I turn ` transparency = false`, the problem is solved
