### ISSUE TITLE
no background contrasts

### ISSUE THREAD

**Issue by Draic** [Tsuzat/NeoSolarized.nvim#24]
loading the plugin I am a bit disappointed in how there are no difference between visual layers. Opening menus on top of a text file and you can't visually tell what is what. I wish colors could be tweaked a little to make distinctions clearer
![no-contrasts](https://github.com/user-attachments/assets/7d3e1b21-b7bc-4bd6-bec8-dd52ab31e547)

**Comment by Tsuzat** [comment]
Hi @Draic, highlight groups can indeed be nuanced, as different users often have varying preferences when it comes to highlighting styles. To address this, many colorscheme plugins offer configuration options that allow users to customize highlights to their liking. For instance, while I personally find the contrast between certain layers to be a bit unusual, I understand that others may appreciate it.

In the default configuration of the colorscheme, transparency is used, which is why Float elements are also transparent. However, if you'd like to give Floats a distinct background color, you can easily adjust this through the plugin's configuration. For example, you could set a different background color for NormalFloat like this:

```lua
-- Add specific hightlight groups
on_highlights = function(highlights, colors) 
    highlights.NormalFloat.bg = colors.bg1
end, 
```

This approach allows you to tailor the appearance according to your preferences.

Happy Coding ❤️
